-- QUERY 1: A SAMPLE JOIN QUERY
SELECT * FROM SALES_DATA  AS S
JOIN
TIME_DATA  AS T
ON
S.[OrderDateKey] = T.TimeKey
ORDER BY S.SALESAMOUNT DESC


-- QUERY 2: ANOTHER SAMPLE JOIN QUERY
SELECT * FROM SALES_DATA  AS S
JOIN
TIME_DATA  AS T
ON
S.[OrderDateKey] = T.TimeKey
JOIN
PRODUCTS_DATA  AS P
ON
S.PRODUCTKEY =  P.PRODUCTKEY 
ORDER BY S.SALESAMOUNT DESC



-- QUERY 3: CLONE / DUPLICATE THE SALES TABLE INTO A NEW TABLE?

SELECT * INTO NEW_TABLE_FOR_SALES FROM SALES_DATA 


-- QUERY 4: APPEND ABOVE TABLE DATA TO ITSELF  -- RUN MULTIPLE TIMES
INSERT INTO NEW_TABLE_FOR_SALES SELECT * FROM NEW_TABLE_FOR_SALES


-- HOW TO AUDIT LONG RUNNING QUERIES?
-- ALL QUERIES ARE AUTO AUDITTED AND TRACKED IN PROCEDURE CACHE
-- PROCEDURE CACHE IS A MEMORY LOCATION (AVAILABLE IN SQL BUFFER SPACE)

SELECT * FROM SYS.DM_EXEC_QUERY_STATS

SELECT plan_handle, total_worker_time, total_worker_time / execution_count AS AVG_EXEC_TIME
FROM SYS.DM_EXEC_QUERY_STATS 
ORDER BY total_worker_time / execution_count DESC 

-- what about the actual queries???

-- GIVEN A PLAN HANDLE, HOW TO EXTRACT THE ACTUAL QUERY?
SELECT * FROM SYS.DM_EXEC_SQL_TEXT(0x06000100B3499C03601F818B3A00000001000000000000000000000000000000000000000000000000000000)

-- WHAT ABOUT ALL QUERIES REPORTED FROM ABOVE PLAN LIST?
SELECT plan_handle, total_worker_time, total_worker_time / execution_count AS AVG_EXEC_TIME,
TEXT
FROM SYS.DM_EXEC_QUERY_STATS 
CROSS APPLY 
SYS.DM_EXEC_SQL_TEXT(plan_handle) 
ORDER BY total_worker_time / execution_count DESC 
