USE PRODUCTDATABASE

SELECT * FROM SALES_DATA 

-- GIVEN A TABLE, HOW TO REPORT THE LIST OF ALL INDEXES?
EXEC SP_HELPINDEX 'SALES_DATA'

-- HOW TO FIND THE ROOT AND OTHER PAGE INFORMATION OF INDEXES?
DBCC CHECKTABLE('SALES_DATA')  -- ENSURE NO ERRORS

DBCC CHECKALLOC() -- LOOKUP FOR TABLE INFORMATION IN THE OUTPUT

-- IAM : INDEX ACCESS MANAGER = THE ADDRESS OF 1ST BRANCH 
-- INDEX ID = 0 MEANS A "HEAP" STRUCTURE


-- HOW TO MEASURE FRAGMENTATION LEVELS? 
-- HOW TO MEASURE THE EXTENT OF FRAGMENTATION OF INDEXES?

SELECT * FROM SYS.dm_db_index_physical_stats(NULL, NULL, NULL, NULL, NULL)

		/*
		IN THE ABOVE DMF : DYNAMIC MANAGEMENT FUNCTION
				DATABASE ID
				OBJECT ID
				INDEX ID
				PARTITION NUMBER
				SAMPLING INTERVAL  = NULL
		*/


SELECT DB_ID('PRODUCTDATABASE')
SELECT * FROM SYS.dm_db_index_physical_stats(32, NULL, NULL, NULL, NULL)

USE North_Windy 
SELECT DB_ID('North_Windy')

SELECT * FROM SYS.dm_db_index_physical_stats(38, NULL, NULL, NULL, NULL)

/*
FRAGMENTATION A PHENOMENA OF SPLITTING / SCATTERING OF INDEX & DATA PAGE CONTENT 
ACCROSS THE DISK. 
THIS MEANS, FRAGMENTATION IS A MEASURE OF NON-CONTIGIOUS DATA STORAGE OF THE DATABASE.

IMAPCT OF FRAGMENTATION : QUERY PERFORAMNCE IMPACT.

IF WE SEE MORE FRAGMENTATION LEVELS THEN REBUILD THE INDEXES

IF WE SEE MODERATE FRAGMENTATION LEVELS THEN REORGANIZE THE INDEXES. REARRANGE FRAGMENTED INDEX PAGES.
*/

-- GIVEN AN OBJECT ID, HOW TO GET THE OBJECT NAME?
SELECT OBJECT_NAME(21575115)  -- TSecurityLinks

-- GIVEN A TABLE, HOW TO GET THE LIST OF INDEXES?
EXEC SP_HELPINDEX 'Orders'

SELECT * FROM SYS.INDEXES WHERE index_id = 2 AND OBJECT_ID = 21575115  -- PK_TSecurityLinks

ALTER INDEX CustomerID
ON Orders
REBUILD

-- ALTERNATE REBUILD OPTIONS:
ALTER INDEX CustomerID
ON Orders
REBUILD
WITH
(
SORT_IN_TEMPDB = ON,		-- DEFAULT SORT AREA FOR INDEX CREATION IS MEMORY. WE ARE NOW USING TEMPDDB.
ONLINE = ON,				-- BY DEFAULT THE INDEX IS STARTED TO USE ONLY AFTER ITS CREATION. 
							-- BUT IF WE SPECIFY THIS OPTION THEN THE ALEREADY CREATED INDEX IS READILY USED 
							-- WHILE THE REMAINING PART OF INDEX IS BEING CREATED.

FILLFACTOR = 80	,			-- EVERY INDEX PAGE IS FULL ONLY 80%
PAD_INDEX = ON				-- ABOVE FILL FACTOR OF INDEX PAGE IS ALSO APPLIED ON DATA PAGES.
)



-- REORGANIZE:
ALTER INDEX CustomerID
ON Orders
REORGANIZE


USE North_Windy
DBCC CHECKALLOC()

SELECT DB_ID() 


-- HOW TO SEE THE INFORMATION FOR GAM, SGAM, IAM, PFS?
DBCC PAGE(38, 1, 203)   -- ANY ERROR / NO OUTPUT OF PFS INFORMATION ??  DBCC TRACEON(3604)




























