CREATE DATABASE [SQLSCHOOL.comAdmin]

USE [SQLSCHOOL.comAdmin]

-- STEP 1: DEFINE A FILEGROUP, MARKED FOR MEMORY OPTIMIZED DATA STORAGE
ALTER DATABASE [SQLSCHOOL.comAdmin]
ADD FILEGROUP MOT_FG 
CONTAINS MEMORY_OPTIMIZED_DATA

-- STEP 2: ADD A FILE INTO ABOVE FILEGROUP
ALTER DATABASE [SQLSCHOOL.comAdmin]
ADD FILE  (NAME = 'MOT_File', filename = 'C:\MOT_Dir')
TO FILEGROUP MOT_FG


-- STEP 3: ENABLE MEMORY OPTIMIZED SNAPSHOT ON THE DATABASE
ALTER DATABASE [SQLSCHOOL.comAdmin] SET MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT ON


-- STEP 4: CREATE THE ACTUAL BASE TABLE - ENABLED FOR MEMORY OPTIMIZATION
  CREATE TABLE dbo.ShoppingCart (   
    ShoppingCartId INT IDENTITY(1,1) PRIMARY KEY NONCLUSTERED,  
    UserId INT NOT NULL INDEX ix_UserId NONCLUSTERED,   
    CreatedDate DATETIME NOT NULL,   
    TotalPrice MONEY  
    ) WITH (MEMORY_OPTIMIZED=ON)   
  

INSERT dbo.ShoppingCart VALUES (8798, SYSDATETIME(), NULL)   
INSERT dbo.ShoppingCart VALUES (23, SYSDATETIME(), 45.4)   
INSERT dbo.ShoppingCart VALUES (80, SYSDATETIME(), NULL)   
INSERT dbo.ShoppingCart VALUES (342, SYSDATETIME(), 65.4)   
GO  


-- HOW TO USE ABOVE TABLE - ENABLED FOR MEMORY OPTIMIZATION?
SELECT * FROM ShoppingCart

SELECT * FROM ShoppingCart
WHERE TotalPrice IS NOT NULL 


WITH CTE
AS
(
SELECT * FROM ShoppingCart
WHERE TotalPrice IS NOT NULL
)
SELECT * FROM CTE


 